
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.1.103:3306/flylive?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wwaacc11..
    driver-class-name: com.mysql.jdbc.Driver
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
#关闭缓存
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#监听文件夹改动
#  devtools:
#    restart:
#      additional-paths: com\\fly\\live\\controller
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fly.live.model

logging:
  level:
    com:
      fly:
        live:
          mapper: DEBUG



#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql